version: "3.7"

services:
  dolt:
    stdin_open: true
    tty: true
    image: dolt
    hostname: dolt
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dolt-data/:/home/doltdata
    network_mode: "host"
    ports:
      - "3306:3306"
volumes:
  dolt-data:
